var list = ["aaa", "bbb", "ccc"];
list[3] = "ddd";
console.log(list);
var list2 = [1, 2, 3];
list2[3] = 100;
console.log(list2);
var agelist = {};
agelist["one"] = 100;
agelist["two"] = 200;
agelist["three"] = 300;
console.log(agelist);
