var num1 = 10;
var num2 = 5;
num1++;
console.log("++: ", num1);
num2--;
console.log("--: ", num2);
var num3 = 10;
var num4 = ++num3;
console.log("전치: " + num3, num4);
var num5 = num3++;
console.log("후치: " + num3, num5);
